import type { Metadata } from "next";
import Link from "next/link";
import PrivacyPolicyBackButton from "@/components/PrivacyPolicyBackButton";

export const metadata: Metadata = {
  title: "Privacy Policy — Ch'rps",
  description: "How Ch'rps collects, uses, and protects information.",
};

// Public, unauthenticated page — see middleware.ts's PUBLIC_PAGE_PATHS.
// Content here is legal copy, not app UI: keep it verbatim when editing:
// changes should come from whoever owns the policy text, not a rewrite
// during an unrelated code change.
export default function PrivacyPolicyPage() {
  return (
    <main className="h-full overflow-y-auto overscroll-none bg-bg">
      <div className="mx-auto max-w-2xl px-6 py-12">
        <PrivacyPolicyBackButton />

        <Link href="/" className="block mt-4 font-brand font-extrabold text-2xl text-olive">
          Ch&apos;rps
        </Link>

        <h1 className="font-heading text-3xl text-text mt-8 mb-2">Ch&apos;rps Privacy Policy</h1>
        <p className="font-mono text-xs text-dim mb-8">Effective date: September 1, 2026</p>

        <div className="space-y-6 font-body text-sm text-text leading-relaxed">
          <p>
            This Privacy Policy explains how Ch&apos;rps (&quot;Ch&apos;rps,&quot; &quot;we,&quot; &quot;us,&quot; or &quot;our&quot;)
            collects, uses, shares, and protects information in connection with the Ch&apos;rps mobile application and
            web dashboard (together, the &quot;Service&quot;). Ch&apos;rps is currently operated by Boston Bijold, an
            individual doing business as Ch&apos;rps, based in Utah. If Ch&apos;rps is later operated through a
            registered business entity, that entity will assume the rights and obligations described here and this
            Policy will be updated accordingly.
          </p>
          <p>
            Ch&apos;rps is a business-to-business (&quot;B2B&quot;) workforce task-verification platform. It is provided to
            companies (&quot;Company&quot; or &quot;Customer&quot;) for use by their managers and employees (&quot;Users&quot;). By using the
            Service, you agree to the collection and use of information as described in this Policy. If you do not
            agree, please do not use the Service.
          </p>

          <Section title="1. Scope and Roles">
            <p>Because Ch&apos;rps is a workplace tool, there are two relevant relationships:</p>
            <ul className="list-disc pl-5 space-y-1">
              <li>
                <strong>Company account data</strong> (e.g., billing, subscription, company settings): Ch&apos;rps acts
                as the data controller.
              </li>
              <li>
                <strong>Employee/User work-activity data</strong> (e.g., task completions, NFC scan logs, schedules):
                Ch&apos;rps processes this data on behalf of, and at the direction of, the Company that administers your
                account. The Company is responsible for ensuring it has the right to share your information with us
                and for informing its employees about its own workplace monitoring and data practices.
              </li>
            </ul>
            <p>
              If you are an employee using Ch&apos;rps because your employer requires it, questions about how your data
              is used inside your workplace should first be directed to your employer. This Policy describes how
              Ch&apos;rps itself handles data across the Service.
            </p>
          </Section>

          <Section title="2. Information We Collect">
            <p>We collect the following categories of information:</p>
            <div className="overflow-x-auto -mx-1">
              <table className="w-full text-left border-collapse text-xs">
                <thead>
                  <tr className="border-b border-border">
                    <th className="py-2 pr-3 font-mono uppercase tracking-wide text-dim">Category</th>
                    <th className="py-2 pr-3 font-mono uppercase tracking-wide text-dim">Examples</th>
                    <th className="py-2 font-mono uppercase tracking-wide text-dim">Source</th>
                  </tr>
                </thead>
                <tbody>
                  {[
                    ["Account information", "Name, email address, profile photo (via Google sign-in), role/title", "You, via Google OAuth"],
                    ["Company information", "Employer/company name, business hours, worksite locations, team roster", "Your employer (the \"Company\")"],
                    ["Task & work-activity data", "NFC tag scan events, timestamps, task names, task-list names, completion status, notes, corrective-action records", "Generated by your use of the App"],
                    ["Device & notification data", "Device push token, Live Activity push token, device type/OS version, app version", "Automatically, from your device"],
                    ["Usage data", "Pages/screens viewed, feature usage, error logs, timestamps of activity", "Automatically, from your use of the App"],
                    ["Communications", "Support requests, feedback, correspondence with us", "You"],
                  ].map(([category, examples, source]) => (
                    <tr key={category} className="border-b border-border align-top">
                      <td className="py-2.5 pr-3 font-medium whitespace-nowrap">{category}</td>
                      <td className="py-2.5 pr-3 text-muted">{examples}</td>
                      <td className="py-2.5 text-muted whitespace-nowrap">{source}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>

            <h3 className="font-heading text-lg text-text mt-6 mb-2">A note on location data</h3>
            <p>
              Ch&apos;rps does not track your GPS location or continuously monitor your movement. Task verification
              works by scanning NFC tags that are physically mounted at fixed locations chosen by the Company (e.g.,
              a walk-in cooler, a host stand). A scan event tells us which tag was tapped and when — not where your
              device is at any other time.
            </p>

            <h3 className="font-heading text-lg text-text mt-6 mb-2">Information we do not collect</h3>
            <ul className="list-disc pl-5 space-y-1">
              <li>We do not collect precise GPS/location tracking of your device.</li>
              <li>We do not access your device contacts, photos, or messages.</li>
              <li>
                We do not currently collect photos as part of task verification (a photo-verification feature may be
                added in the future and, if so, this Policy will be updated first).
              </li>
              <li>
                We do not currently charge for the Service and do not collect or store any payment card information.
                If paid subscriptions are introduced in the future, this Policy will be updated to describe how
                billing information is handled before that change takes effect.
              </li>
            </ul>
          </Section>

          <Section title="3. How We Use Information">
            <p>We use the information described above to:</p>
            <ul className="list-disc pl-5 space-y-1">
              <li>
                Provide, operate, and maintain the Service, including shift-based task lists, NFC scan verification,
                and recurring/anytime tasks;
              </li>
              <li>Authenticate Users via Google sign-in and maintain secure sessions;</li>
              <li>
                Send push notifications and Live Activity updates related to task lists, reminders, and escalations;
              </li>
              <li>
                Generate analytics and reporting for Company managers and administrators (e.g., completion rates,
                missed-task trends);
              </li>
              <li>Operate corrective-action and escalation workflows configured by a Company;</li>
              <li>
                Maintain the security, integrity, and proper functioning of the Service, including diagnosing
                technical issues;
              </li>
              <li>Communicate with you about the Service, including support requests you initiate;</li>
              <li>Comply with legal obligations and enforce our agreements.</li>
            </ul>
            <p>
              We do not sell personal information, and we do not use employee task-activity data to serve
              third-party advertising.
            </p>
          </Section>

          <Section title="4. How We Share Information">
            <p>We share information only as needed to operate the Service, and with the following categories of recipients:</p>
            <ul className="list-disc pl-5 space-y-1">
              <li>
                <strong>Your employer (Company):</strong> Managers and administrators at your Company can see task
                completion records, timestamps, and related activity data for Users at that Company, as part of the
                core function of the Service.
              </li>
              <li>
                <strong>Service providers:</strong> We use third-party vendors to host and operate the Service,
                including Vercel (application hosting), MongoDB Atlas (database hosting), Apple Inc. (push
                notifications via APNs), and Google (sign-in authentication). These providers process data only as
                necessary to perform services for us and are bound by their own data-protection obligations.
              </li>
              <li>
                <strong>Legal and safety reasons:</strong> We may disclose information if required by law, subpoena,
                or other legal process, or if we believe in good faith that disclosure is necessary to protect the
                rights, property, or safety of Ch&apos;rps, our users, or others.
              </li>
              <li>
                <strong>Business transfers:</strong> If Ch&apos;rps is involved in a merger, acquisition, financing, or
                sale of assets, information may be transferred as part of that transaction, subject to this Policy
                or a successor policy.
              </li>
            </ul>
            <p>We do not share personal information with third parties for their own independent marketing purposes.</p>
          </Section>

          <Section title="5. Data Retention">
            <p>
              We retain Company and User information for as long as the Company maintains an active subscription,
              and for a reasonable period afterward to allow for account reactivation, comply with legal or
              accounting obligations, and resolve disputes. A Company administrator may request deletion of its
              account and associated data by contacting us; certain records may be retained where required by law or
              legitimate business need (such as billing records).
            </p>
          </Section>

          <Section title="6. Data Security">
            <p>
              We use reasonable administrative, technical, and organizational safeguards designed to protect
              information against unauthorized access, alteration, disclosure, or destruction, including encrypted
              connections (HTTPS/TLS), authenticated sessions via Google OAuth, and access controls scoped by
              company and role. No method of transmission or storage is completely secure, and we cannot guarantee
              absolute security.
            </p>
          </Section>

          <Section title="7. Your Choices and Rights">
            <ul className="list-disc pl-5 space-y-1">
              <li>
                <strong>Access and correction:</strong> You may review and update certain account information within
                the app, or by asking your Company administrator or contacting us directly.
              </li>
              <li>
                <strong>Push notifications:</strong> You can disable push notifications at any time through your
                device settings, though this may limit certain features (e.g., task-start alerts, Live Activities).
              </li>
              <li>
                <strong>Account deletion:</strong> Because Ch&apos;rps accounts are provisioned by an employer,
                deletion requests are generally handled by your Company administrator. You may also contact us
                directly and we will coordinate with the relevant Company as appropriate.
              </li>
            </ul>
            <p>
              If you are a resident of a U.S. state with a comprehensive privacy law, you may have additional rights
              regarding your personal information under that state&apos;s law; you may contact us using the
              information below to make a request, and we will respond consistent with applicable law.
            </p>
          </Section>

          <Section title="8. Children's Privacy">
            <p>
              Ch&apos;rps is a workplace tool intended for use by employees of business Customers and is not directed
              to children. We do not knowingly collect personal information from anyone under the age of 16. If you
              believe a child has provided us with personal information, please contact us and we will take
              appropriate steps to delete it.
            </p>
          </Section>

          <Section title="9. Cookies and Similar Technologies">
            <p>
              Our web dashboard may use essential cookies and similar technologies (such as session identifiers)
              required for authentication and core functionality, and may use limited analytics tools to understand
              how the Service is used and to improve it. We do not use cookies for third-party advertising.
            </p>
          </Section>

          <Section title="10. International Users">
            <p>
              The Service is hosted in the United States and intended for use by Companies and Users located in the
              United States. If you access the Service from outside the United States, your information will be
              transferred to, stored, and processed in the United States.
            </p>
          </Section>

          <Section title="11. Changes to This Policy">
            <p>
              We may update this Privacy Policy from time to time to reflect changes in our practices, the Service,
              or applicable law. We will post the updated Policy with a revised &quot;Effective date&quot; above, and, for
              material changes, will provide additional notice where appropriate (such as in-app notice or email to
              Company administrators).
            </p>
          </Section>

          <Section title="12. Contact Us">
            <p>
              If you have questions, concerns, or requests regarding this Privacy Policy or your personal
              information, please contact us at:
            </p>
            <p className="font-mono text-xs leading-6">
              Ch&apos;rps
              <br />
              Attn: Boston Bijold
              <br />
              Email: bostonrbijold@gmail.com
              <br />
              Location: Utah, United States
            </p>
            <p className="text-xs text-dim italic">
              (A dedicated company email will replace the address above once available; the current version of this
              Policy is always the one linked in the app and on our website.)
            </p>
          </Section>

          <Section title="13. Governing Law">
            <p>
              This Policy and any dispute arising from it will be governed by the laws of the State of Utah, without
              regard to its conflict-of-laws principles, unless otherwise required by applicable law.
            </p>
          </Section>
        </div>
      </div>
    </main>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section>
      <h2 className="font-heading text-xl text-text mb-2">{title}</h2>
      <div className="space-y-3">{children}</div>
    </section>
  );
}
